---
title: "Variant tracker equations"
output: html_document
date: '2022-04-05'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Equations

We're interested in the relative growth rate of variant $i$ in country $k$. Because the model I'm proposing here is only within country $k$, I'm going to omit the $k$ subscript for notational clarity, but it is implicit. I consider briefly an extension below that considers country, but there are additional biological and intepretational complexities to consider in this case that make it potentially incoherent.

If we consider all sequences observed over the past 6 months (6 months ago $t = 0$; $t \in \mathbb{W}$), on day $t$ we observe $N_t$ sequences total ($N_t \in \mathbb{W}$), of which $n_{it}$ sequences are of variant lineage $i$ ($n_{it} \in \mathbb{W}; N_t = \sum_i n_{it}$). Then the set of observed variant lineages on that day is $i_t \in \{1, ..., I\}$ where I is the number of observed lineages over the entire time period. Although this quantity changes over time due to evolution, we consider it here to be both fixed and known (i.e. the number of PANGO lineages known today). If $p_{it} = \frac{n_{it}}{N_t}$, then the set of observed variant proportions on day $t$ is $p_t = \{p_{it}, ..., p_{It}\}$, $p \in [0, 1]$. Assuming that the random draw $n_{i, t}$ is independent (albeit correlated) with the random draw $n_{i, t+1}$, this scenario describes a multinomial distribution, which has probability mass function (PMF):

$$
f(n_{it}, ..., n_{It}; N_t, p_{it}, ..., p_{It}) = 
\frac{N_t!}{n_{it}! ... n_{It}!} p_{it} \times ... \times p_{It}
$$
However, this PMF conditions on the _known_ true probabilities of drawing $i$; these probabilities are of course unknown. With vector of lineages $\{i, ..., j, I\}$, where $I$ is the dominant local variant, this PMF and its unknowns motivate the regression model formulation

$$
ln\left(\frac{P(X = i)}{P(X = I)} \right)= \beta_{0i} + \beta_{1i} t
\\
\vdots
\\
ln\left(\frac{P(X = j)}{P(X = I)} \right)= \beta_{0j} + \beta_{1j} t
$$
for each category $i$ except the base case $I$, producing $I-1$ cases. Classically, the intercepts ($\beta_{0i}$) in a multinomial logistic regression are interpreted as the average difference in log odds being in category $i$ than category $I$ when the coefficients are 0 (i.e. $t = 0$). The slope, $\beta_{1i}$ is interpreted as the average change in log odds of being in category $i$ relative to category $I$ for a unit change in the covariate $t$. Fit to observed variant proportions, the slope coefficients describe the difference in intrinsic growth rates for the variant in the numerator and the variant in the denominator (i.e. $\beta_{1i} = r_i - r_I$ where $r_I$ is the intrinsic growth rate of the dominant variant). However, this model does not produce an estimate of the actual intrinsic growth rates (i.e. $r_i$ or $r_I$) because fitting $I$ cases would make the model overdetermined.

Despite the ability of the multinomial likelihood to account for changes in sample size over time (i.e. $N_t$), the $\beta_{1i}$ coefficients are still likely to be biased at small sample sizes or when first observed. Many of these variants will be just as fit or roughly similar to the current dominant variants (i.e. neutral evolution), but we are only able to observe the mutant lineages that grow more quickly than the dominant lineage -- regardless of whether this apparent growth advantage is truly real or simply stochastic and transient. As a result, of the variants that are growing quickest at time $t$, many will, on average, have MLE $\hat \beta_{1i}$ coefficients stochastically higher than their true average growth rate $\beta_{1i}$. If they were not growing more quickly at the current moment, we wouldn't be able to observe them. In other words, our observations are a biased subset of the entire population -- but this bias is transient and will decrease with time and number of samples. It's a function of our observation process. If we just fit a multinomial to these samples, we're almost certainly going to see our estimates decline over time (regress to the mean) as we get more data because we're inducing a selection bias in the data we're considering.


We can decrease this bias by specifying a model that shrinks these small sample size, uncertain $\beta_{1i}$ coefficients away from more extreme estimates and towards values we think are more likely. However, in order to shrink the inflated $\beta_{1i}$ coefficients to smaller values, we need to specify: 1) what we are shrinking these coefficients towards and 2) the strength of the shrinkage. In other words, we need specify what it means to be extreme and what it means to reasonable. In a Bayesian model we perform this shrinkage through two separate, but related mechanisms: specifying a candidate generative process through which the data are observed (AKA the model or, more formally, the likelihood) and specifying our prior beliefs (more formally, the prior likelihood). One obvious choice for a ``reasonable" model of $\beta_{1i}$ that would perform shrinkage is one in which most new lineages are expected to be basically similar to the lineages that have already occurred, unless the data strongly suggest otherwise. Biologically this model would make sense; most new lineages have a few genetic mutations that differentiate them from their parent lineages, but otherwise remain the same. It seems reasonable, therefore, that these new lineages should have growth rates similar to their parent lineages most of the time, sometimes growing little bit quicker and sometimes a little bit slower, but occasionally a particularly impactful constellation of mutations will lead to a radical change. More technically, this description is of a generative process in which most $\beta_{1i}$ values are similar to the overall mean of the growth rates, $\mu_{\beta_1}$ -- this is the value towards which we would shrink $\beta_{1i}$ values. The strength of the shrinkage is controlled by $\sigma^2_{\beta_1}$, the variance of the $\beta_{1i}$ values. If most $\beta_{1i}$ values are tightly clustered around $\mu_{\beta_1}$, their variance would be low and we would be surprised to see a very high $\beta_{1i}$ value, so we would see more shrinkage of that outlier. On the other hand, if there's high variance in $\beta_{1i}$ values, we would see less shrinkage because an outlier would be more expected. Even more technically, this process suggests a unimodal, symmetric distribution over the $\beta_{1i}$ values. In building this model we should evaluate a range of distributions that fit this description (i.e. Student's $t$ distributions with varying degrees of freedom), but for the rest of this document I'll use a Normal distribution for notational simplicity and clarity. While this solution is imperfect because it does not model the actual Bernoulli observation process (which would require modeling both the observed $\hat \beta_{1i}$ and $\beta_{1i}$ as well as the probability of observing $i$ as an increasing function of $\hat \beta_{1i}$), it will help to somewhat reduce the bias.

If we consider relative variant fitness as drawn from a distribution $\beta_{1i} \sim N(\mu_{\beta_1}, \sigma^2_{\beta_1})$, new variants with small sample sizes will be pulled toward $\mu_{\beta_1}$ with the strength of the shrinkage controlled by $\sigma^2_{\beta_1}$. The $\sigma^2_{\beta_1}$ parameter in the model will be informed by both observed data and our prior expectation of its value, which we set as $Exp(3)$ as a first pass. Since these differences in growth rates are relative to the dominant variant as the base case, a $N(-1, 1)$ prior distribution is likely appropriate for $\mu_{\beta_1}$, which assumes that a new variant's intrinsic growth is on average worse than the base case (dominant variant). If the data are looser or wider than this prior value, the $\sigma^2_{\beta_1}$ parameter will be updated during the model by the information present in the data.

## Multi-country extension

Comparison of intrinsic growth rates from logistic growth models across time or location is complicated by the dependence of these growth rates on local conditions. One strain may be fitter in the presence of particular conditions, driven by the contact or immunity landscape, but these conditions may be transient or particular to that location. A strain that is more fit in one setting is not necessarily more fit in another.

However, if one is willing to relax the interpretability of their model, one could extend these multinomial models across countries -- borrowing information from conditions in one country to inform the model about those of another. This approach can help handle problems of limited sampling in one country and, vice versa, help increase the uncertainty about relative fitness to our true level of skepticism when it is artificially deflated by very high sampling in one or two locations.

This can be accomplished by generalizing the $\beta_{1i} \sim N(\mu_{\beta_1}, \sigma^2_{\beta_1})$ distribution into a multi-country extension: $\beta_{1i}^K \sim MVN(\mu_{\beta_1}^K, \Sigma_{\beta_1}^{K \times K})$. Here, each variant lineage $I$ has a single $K$-length vector $\beta_{1i}^K$ as a single realization from the multivariate normal distribution, in which each element $\beta_{1i}$ is one variant lineage in country $k$ (from the set of all countries $\{k, ..., K\}$, so there are $I$ of these $K$ length vectors). The mean over all lineages of the relative growth rate of variants in that country ($E[\beta_{1}|k, \{i, ..., I\}]$) is described by the $K$-length vector $\mu_{\beta_1}^K$, in which each element is the expected relative growth rate of a lineage in that country. Rather than a single $\sigma^2_{\beta_1}$ parameter, we can produce a $K \times K$ $\Sigma_{\beta_1}$ covariance matrix, describing the similarity of conditions in one country with those of another. The $\Sigma_{\beta_1}$ matrix can be decomposed into scale parameters $\tau$ and a correlation matrix $\Omega$ with a more interpretable LKJ prior. The expected variability of the relative growth rates of variants within the country is described by diag$(\Sigma_{\beta_1}^{K \times K})$, the same as the $\sigma^2_{\beta_1}$ values in the original model. The off-diagonal elements of $\Omega^{K \times K}$ describe the expected correlation of the relative growth in country $k$ with that of another country -- in other words the amount of information sharing across countries. If the observed relative growth rate of variant $i$ is higher in country $k$, the the off-diagonal elements of $\Omega^{K \times K}$ determine how strongly we should expect to be higher in other countries too. 

In order to maintain the ability to share information across variants that have only been sparingly observed, the mean differences in growth rates are themselves drawn from a hierarchical distribution: $\mu_k \sim N(\mu_{\mu}, \sigma_{\mu})$. This hierarchical distribution is similar to the hierarchical distribution that implemented shrinkage on the growth rates in the single country model, but in this case it is instead on the mean growth rates averaged over countries. The intercepts, $\beta_{0, k}$ are each drawn from lineage specific normal distributions, with no correlation matrix across countries: $\beta_{0, i, k} \sim N(\mu_{0i}, \sigma_{0i})$. This approach allows for different timing, emergence, and patterns of spread for each variant while still enforcing a roughly similar introduction time for different variants across countries.


Less technically, we would be jointly estimating a vector of global mean growth rates for each variant ($\mu_{\beta_1}^K$) over all countries. The individual observations of the growth rates in each country would be shrunk towards the overall global mean with strength of shrinkage controlled by the country-specific variances across the countries (diag$(\Sigma_{\beta_1}^{K \times K})$). Information sharing about variants is then also possible across countries, with the correlations between countries describing how strongly we expect individual countries to be like each other. If the correlation between countries $k$ and $m$ is high and if $\beta_{1i}$ is observed higher than $\mu_{\beta_1, k}$ in country $k$, then we would likewise expect it to be higher than $\mu_{\beta_1, m}$ in country $m$. We would be assuming that each variant (in every country) is a single observation from this multivariate normal distribution with the similarities across countries following the pattern described by its correlation/covariance matrix.


